packages:
  - name: app
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    deps:
      - components/common-go/grpc:lib
      - components/common-go/kubernetes:lib
      - components/common-go/log:lib
      - components/common-go/namegen:lib
      - components/content-service-api/go:lib
      - components/image-builder-api/go:lib
      - components/public-api/go:lib
      - components/registry-facade-api/go:lib
      - components/ws-daemon-api/go:lib
      - components/ws-manager-api/go:lib
      - components/ws-manager-bridge-api/go:lib
    env:
      - CGO_ENABLED=0
    config:
      packaging: app
      dontTest: true
