# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: batch/v1
kind: Deployment
metadata:
  name: status-informer
  labels:
    app: gitpod
    component: gitpod-installer
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: gitpod
        component: gitpod-installer
    spec:
      serviceAccountName: installer
      restartPolicy: OnFailure
      containers:
        - name: installer
          # This will normally be the release tag - using this tag as need the license evaluator
          image: "eu.gcr.io/gitpod-core-dev/build/installer:sje-installer-mini-config.0"
          volumeMounts:
            - mountPath: /config-patch
              name: config-patch
              readOnly: true
            - mountPath: /mnt/node0
              name: node-fs0
              readOnly: true
          env:
            - name: CONFIG_FILE
              value: /tmp/gitpod-config.yaml
            - name: CONFIG_PATCH_FILE
              value: /config-patch/gitpod-config-patch.yaml
            - name: CONTAINERD_DIR_K3S
              value: /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
            - name: CONTAINERD_SOCKET_K3S
              value: /run/k3s/containerd/containerd.sock
            - name: GITPOD_OBJECTS
              value: /tmp/gitpod
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e

              echo "Gitpod: Status Informess job failed - goodbye"
      volumes:
        - name: config-patch
          configMap:
            name: gitpod-config-patch
        - name: node-fs0
          hostPath:
            path: /
            type: Directory
