# @todo(sje): cert-manager may become optional in future, to allow for users to install their own version
apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: cert-manager
spec:
  chart:
    name: cert-manager
    chartVersion: 1.7.0
  helmVersion: v3
  useHelmInstall: true
  optionalValues:
    - when: '{{repl ConfigOptionNotEquals "certmanager_config_patch" "" }}'
      recursiveMerge: false
      values:
        repl{{ if ConfigOptionNotEquals "certmanager_config_patch" ""}}repl{{ printf (ConfigOption "certmanager_config_patch") | nindent 8}}repl{{ end}}
