# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: gitpod
spec:
  title: Gitpod
  icon: ""
  allowRollback: true
  kubectlVersion: ">= 1.21.0"
  # daemonsets are not supported yet
  statusInformers:
    - deployment/status-informer