packages:
  - name: lib
    type: go
    deps:
      - components/common-go/grpc:lib
      - components/common-go/util:lib
      - components/common-go/kubernetes:lib
      - components/content-service-api/go:lib
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    config:
      packaging: library
      dontTest: false
