image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:kylos101-kubecdl-home.1
workspaceLocation: gitpod/gitpod-ws.code-workspace
checkoutLocation: gitpod
ports:
    - port: 1337
      onOpen: open-preview
    - port: 3000
      onOpen: ignore
    - port: 3001
      onOpen: ignore
    - port: 3306
      onOpen: ignore
    - port: 4000
      onOpen: ignore
    # VNC
    - port: 5900
      onOpen: ignore
    # noVNC
    - port: 6080
      onOpen: ignore
    # Werft
    - port: 7777
      onOpen: ignore
    - port: 9229
      onOpen: ignore
    # Go proxy
    - port: 9999
      onOpen: ignore
    - port: 13001
      onOpen: ignore
    # Dev Theia
    - port: 13444
    # Used when using port-forwarding to SSH to preview environment VMs
    - port: 8022
      onOpen: ignore
tasks:
    - name: Remove GCP_ADC_FILE
      command: |
          if [[ -n "${GCP_ADC_FILE}" ]]; then
            echo "$GCP_ADC_FILE" > "/home/gitpod/.config/gcloud/application_default_credentials.json"
            yes | gcloud auth application-default revoke
            gp env -u GCP_ADC_FILE
          fi
          exit 0
    # This task takes care of configuring your workspace so it can manage and interact
    # with preview environments.
    - name: Preview environment configuration
      init: leeway run dev/preview/previewctl:install
      command: INSTALL_CONTEXT=true leeway run dev/preview:configure-workspace
    - name: Installer dependencies
      init: |
          (cd install/installer && make deps)
          exit 0
    - name: TypeScript
      init: yarn --network-timeout 100000 && yarn build
    - name: Go
      before: pre-commit install --install-hooks
      init: |
          ./components/gitpod-protocol/go/scripts/generate-config.sh
          leeway exec --filter-type go -v -- go mod verify
      openMode: split-right
vscode:
    extensions:
        - EditorConfig.EditorConfig
        - golang.go
        - hashicorp.terraform
        - ms-azuretools.vscode-docker
        - ms-kubernetes-tools.vscode-kubernetes-tools
        - stkb.rewrap
        - zxh404.vscode-proto3
        - matthewpi.caddyfile-support
        - heptio.jsonnet
        - timonwong.shellcheck
        - fwcd.kotlin
        - dbaeumer.vscode-eslint
        - esbenp.prettier-vscode
        - akosyakov.gitpod-monitor
profiles:
    # implicit profile derived from usual .gitpod.yml config
    default:
      # display name shown in New Workspace window under Context URL, if only default profile then omitted 
      name: Gitpod development
    jb:
      name: Gitpod JetBrains integration
      tasks:
          - name: Java
            init: leeway run components/supervisor-api:generate-java
            command: |
                leeway exec --package components/supervisor-api/java:lib --package components/gitpod-protocol/java:lib -- ./gradlew build
                leeway exec --package components/ide/jetbrains/backend-plugin:plugin-latest --package components/ide/jetbrains/gateway-plugin:publish-latest --parallel -- ./gradlew buildPlugin
      workspaceLocation: gitpod/jb.code-workspace
      jetbrains:
        intellij:
          vmoptions: -Xmx4g
    vscode:
      name: Gitpod VS Code integration
      include: 
        - config: gitpod-code/.gitpod.yml
          profile: default
      additionalRepositories:
      - url: https://github.com/gitpod-io/gitpod-code
        checkoutLocation: gitpod-code
      workspaceLocation: gitpod/vscode.code-workspace
    ide:
      name: Gitpod IDE development
      include:
        - config: gitpod/.gitpod.yml
          profile: jb
        - config: gitpod/.gitpod.yml
          profile: vscode
      workspaceLocation: gitpod/ide.code-workspace
