packages:
  - name: app
    type: go
    srcs:
      - "pkg/agent/testdata/**"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    deps:
      - components/common-go:lib
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    config:
      packaging: app
      buildCommand: ["go", "build", "-trimpath", "-ldflags", "-buildid= -w -s -X 'github.com/gitpod-io/gitpod/autoscaler-expander/cmd.Version=commit-${__git_commit}'"]
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      buildArgs:
        VERSION: ${version}
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/autoscaler-expander:${version}
        - ${imageRepoBase}/autoscaler-expander:commit-${__git_commit}
