packages:
    - name: app
      type: go
      srcs:
        - go.mod
        - go.sum
        - "**/*.go"
      env:
        - CGO_ENABLED=0
      deps:
        - components/common-go:lib
        - components/policy-agent-api/go:lib
      config:
        packaging: app
    - name: docker
      type: docker
      deps:
        - :app
      argdeps:
        - imageRepoBase
      config:
        buildArgs:
          VERSION: ${version}
        dockerfile: leeway.Dockerfile
        metadata:
          helm-component: policyAgent
        image:
          - ${imageRepoBase}/policy-agent:commit-${__git_commit}