packages:
  - name: app
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    config:
      packaging: app
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: wsDaemon.cgroupCustomizer
      image:
        - ${imageRepoBase}/cgroup-customizer:${version}
        - ${imageRepoBase}/cgroup-customizer:commit-${__git_commit}
