packages:
  - name: app
    type: go
    srcs:
      - go.mod
      - go.sum
      - "**/*.go"
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    config:
      dontTest: true
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/changelog:${version}
        - ${imageRepoBase}/changelog:commit-${__git_commit}
scripts:
  - name: update
    deps:
      - dev/changelog:app
    description: Updates the CHANGELOG.md from release-notes blocks in the description of PRs
    script: |
      changelog -t $GITHUB_TOKEN -o $GITHUB_ORG -r $GITHUB_REPO -b $GIT_BRANCH
