# permissions for end users to edit installations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installation-editor-role
rules:
- apiGroups:
  - install.gitpod.io
  resources:
  - installations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - install.gitpod.io
  resources:
  - installations/status
  verbs:
  - get
