# permissions for end users to view installations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installation-viewer-role
rules:
- apiGroups:
  - install.gitpod.io
  resources:
  - installations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - install.gitpod.io
  resources:
  - installations/status
  verbs:
  - get
