packages:
  - name: docker
    type: docker
    deps:
      - :bundle
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: workspace.devcontainer
      image:
        - ${imageRepoBase}/ide/devcontainer:${version}
        - ${imageRepoBase}/ide/devcontainer:commit-${__git_commit}
  - name: bundle
    type: generic
    srcs:
      - "supervisor-ide-runtime-config.json"
    deps:
      - :app
      - :cli
    config:
      commands:
        - ["mkdir", "-p", "ide/devcontainer"]
        - ["cp", "supervisor-ide-runtime-config.json", "./ide/"]
        - ["rm", "-rf", "supervisor-ide-runtime-config.json"]
        - ["cp", "components-ide-devcontainer--app/launcher", "./ide/devcontainer/"]
        - ["rm", "-rf", "components-ide-devcontainer--app"]
        - ["cp", "-aR", "components-ide-devcontainer--cli/node_modules", "./ide/devcontainer/"]
        - ["rm", "-rf", "components-ide-devcontainer--cli"]
  - name: cli
    type: yarn
    srcs:
      - package.json
    config:
      yarnLock: ${coreYarnLockBase}/../yarn.lock
      dontTest: false
      packaging: archive
  - name: app
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    deps:
      - components/gitpod-protocol/go:lib
      - components/supervisor-api/go:lib
      - components/common-go:lib
    config:
      packaging: app
      buildCommand: ["go", "build", "-trimpath", "-ldflags", "-buildid= -w -s -X 'github.com/gitpod-io/gitpod/devcontainer/launcher.Version=commit-${__git_commit}'"]
