packages:
  - name: docker
    type: generic
    argdeps:
      - version
    deps:
      - :intellij
      - :intellij-eap
      - :goland
      - :goland-eap

  - name: intellij
    type: docker
    srcs:
      - "startup.sh"
      - "supervisor-ide-config_intellij.json"
      - "status/go.mod"
      - "status/main.go"
    deps:
      - components/ide/jetbrains/backend-plugin:plugin
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: workspace.desktopIdeImages.intellij
      buildArgs:
        JETBRAINS_BACKEND_URL: "https://download.jetbrains.com/idea/ideaIU-2021.3.tar.gz"
        SUPERVISOR_IDE_CONFIG: supervisor-ide-config_intellij.json
      image:
        - ${imageRepoBase}/ide/intellij:${version}
        - ${imageRepoBase}/ide/intellij:commit-${__git_commit}

  - name: intellij-eap
    type: docker
    srcs:
      - "startup.sh"
      - "supervisor-ide-config_intellij.json"
      - "status/go.mod"
      - "status/main.go"
    deps:
      - components/ide/jetbrains/backend-plugin:plugin
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: workspace.desktopIdeImages.intellijEap
      buildArgs:
        JETBRAINS_BACKEND_URL: "https://download.jetbrains.com/idea/ideaIU-213.5744.18.tar.gz"
        SUPERVISOR_IDE_CONFIG: supervisor-ide-config_intellij.json
      image:
        - ${imageRepoBase}/ide/intellij-eap:${version}
        - ${imageRepoBase}/ide/intellij-eap:commit-${__git_commit}

  - name: goland
    type: docker
    srcs:
      - "startup.sh"
      - "supervisor-ide-config_goland.json"
      - "status/go.mod"
      - "status/main.go"
    deps:
      - components/ide/jetbrains/backend-plugin:plugin
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: workspace.desktopIdeImages.goland
      buildArgs:
        JETBRAINS_BACKEND_URL: "https://download.jetbrains.com/go/goland-2021.2.4.tar.gz"
        SUPERVISOR_IDE_CONFIG: supervisor-ide-config_goland.json
      image:
        - ${imageRepoBase}/ide/goland:${version}
        - ${imageRepoBase}/ide/goland:commit-${__git_commit}

  - name: goland-eap
    type: docker
    srcs:
      - "startup.sh"
      - "supervisor-ide-config_goland.json"
      - "status/go.mod"
      - "status/main.go"
    deps:
      - components/ide/jetbrains/backend-plugin:plugin
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: workspace.desktopIdeImages.golandEap
      buildArgs:
        JETBRAINS_BACKEND_URL: "https://download.jetbrains.com/go/goland-213.5744.26.tar.gz"
        SUPERVISOR_IDE_CONFIG: supervisor-ide-config_goland.json
      image:
        - ${imageRepoBase}/ide/goland-eap:${version}
        - ${imageRepoBase}/ide/goland-eap:commit-${__git_commit}
