apiVersion: kots.io/v1beta1
kind: License
metadata:
  name: communityunstable
spec:
  appSlug: gitpod
  channelID: 259YYGjrDCpnE0nGmF3yIKIV3zs
  channelName: Unstable
  customerName: Community (Unstable)
  endpoint: https://replicated.app
  entitlements:
    customerId:
      title: Customer ID
      value: ""
      valueType: String
    domain:
      title: Domain
      value: ""
      valueType: String
    expires_at:
      description: License Expiration
      title: Expiration
      value: ""
      valueType: String
    levelId:
      isHidden: true
      title: License level
      value: 1
      valueType: Integer
    seats:
      title: User seats
      value: 0
      valueType: Integer
  isGitOpsSupported: true
  isIdentityServiceSupported: true
  isNewKotsUiEnabled: true
  isSnapshotSupported: true
  licenseID: 26QkP1TBm7krczl8eYT6sDXLRRA
  licenseSequence: 7
  licenseType: community
  signature: eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pWTI5dGJYVnVhWFI1ZFc1emRHRmliR1VpZlN3aWMzQmxZeUk2ZXlKc2FXTmxibk5sU1VRaU9pSXlObEZyVURGVVFtMDNhM0pqZW13NFpWbFVObk5FV0V4U1VrRWlMQ0pzYVdObGJuTmxWSGx3WlNJNkltTnZiVzExYm1sMGVTSXNJbU4xYzNSdmJXVnlUbUZ0WlNJNklrTnZiVzExYm1sMGVTQW9WVzV6ZEdGaWJHVXBJaXdpWVhCd1UyeDFaeUk2SW1kcGRIQnZaQ0lzSW1Ob1lXNXVaV3hKUkNJNklqSTFPVmxaUjJweVJFTndia1V3YmtkdFJqTjVTVXRKVmpONmN5SXNJbU5vWVc1dVpXeE9ZVzFsSWpvaVZXNXpkR0ZpYkdVaUxDSnNhV05sYm5ObFUyVnhkV1Z1WTJVaU9qY3NJbVZ1WkhCdmFXNTBJam9pYUhSMGNITTZMeTl5WlhCc2FXTmhkR1ZrTG1Gd2NDSXNJbVZ1ZEdsMGJHVnRaVzUwY3lJNmV5SmpkWE4wYjIxbGNrbGtJanA3SW5ScGRHeGxJam9pUTNWemRHOXRaWElnU1VRaUxDSjJZV3gxWlNJNklpSXNJblpoYkhWbFZIbHdaU0k2SWxOMGNtbHVaeUo5TENKa2IyMWhhVzRpT25zaWRHbDBiR1VpT2lKRWIyMWhhVzRpTENKMllXeDFaU0k2SWlJc0luWmhiSFZsVkhsd1pTSTZJbE4wY21sdVp5SjlMQ0psZUhCcGNtVnpYMkYwSWpwN0luUnBkR3hsSWpvaVJYaHdhWEpoZEdsdmJpSXNJbVJsYzJOeWFYQjBhVzl1SWpvaVRHbGpaVzV6WlNCRmVIQnBjbUYwYVc5dUlpd2lkbUZzZFdVaU9pSWlMQ0oyWVd4MVpWUjVjR1VpT2lKVGRISnBibWNpZlN3aWJHVjJaV3hKWkNJNmV5SjBhWFJzWlNJNklreHBZMlZ1YzJVZ2JHVjJaV3dpTENKMllXeDFaU0k2TVN3aWRtRnNkV1ZVZVhCbElqb2lTVzUwWldkbGNpSXNJbWx6U0dsa1pHVnVJanAwY25WbGZTd2ljMlZoZEhNaU9uc2lkR2wwYkdVaU9pSlZjMlZ5SUhObFlYUnpJaXdpZG1Gc2RXVWlPakFzSW5aaGJIVmxWSGx3WlNJNklrbHVkR1ZuWlhJaWZYMHNJbWx6UjJsMFQzQnpVM1Z3Y0c5eWRHVmtJanAwY25WbExDSnBjMGxrWlc1MGFYUjVVMlZ5ZG1salpWTjFjSEJ2Y25SbFpDSTZkSEoxWlN3aWFYTlRibUZ3YzJodmRGTjFjSEJ2Y25SbFpDSTZkSEoxWlN3aWFYTk9aWGRMYjNSelZXbEZibUZpYkdWa0lqcDBjblZsZlgwPSIsImlubmVyU2lnbmF0dXJlIjoiZXlKc2FXTmxibk5sVTJsbmJtRjBkWEpsSWpvaVpHZFlZWFpwWTFCNWJFVm9ZbGR1U2xkNE1qRm9XVkJtTTI5akswbDBRblJ3TlRGRGRWY3pWbE5ETjFBd1RHUm9RVEJOZDJOU2NUVTJUM1F6Ym5oUFpFaHZiblpOTXpZd2NHZFNZV1JTTnpjd2IxcFJkVUkxVnpCMFoxbDBiMkZTTldWaU5WVXdhMjFOVTFwSGVGRldOMHRGVFZsU2NsQjZaVVZxUVM4MFQySmhPVXd5TVhaRWNtaGlNa0Y2ZDFkM2Myb3djV3B6Tm1aUUx6Tm1jREZ0WTNSWk0xZHFOak5yVG1WaVVTdE1XRnBSUzFSSVJGRTFVVlZKY1hkQlpGaG9VWFJ3YUc5Mk5YQmFTamczT1V0VlUzcEhOelV2VUZGR2FERkdNRmt6ZEZBclNGY3JUMU56TDA4MFZYa3hSMVF2ZVVWNmVHTkNTREpFS3pocFFUa3JOekJuWkdweFN6TllRbGszYVdwTVkzZzJTVVE0UzAxaU0zbDViWGxUUjBwc1NGcEdXVlJxWmtoS1IzUlJSMVZLZEdkT01qVllla0l6V205amFXUktRVnB6ZEdjdmJXUktRbWhSYkNzelNFTk5LMUJsUTJSM1BUMGlMQ0p3ZFdKc2FXTkxaWGtpT2lJdExTMHRMVUpGUjBsT0lGQlZRa3hKUXlCTFJWa3RMUzB0TFZ4dVRVbEpRa2xxUVU1Q1oydHhhR3RwUnpsM01FSkJVVVZHUVVGUFEwRlJPRUZOU1VsQ1EyZExRMEZSUlVGdk5XNTZPVmxFUzFOUlJtVndiMkphVmpBNWQxeHVXRXRsTjNSc1RGVlZWVzVUWlRnd01FZERTMVJEVkZwemJtOXFkVUpoZVdwcFMyUjNXa1F6VlZSS2NUQkVhVzlCY2xoVmEyaEVOR3RtZEROdFJGUTNSbHh1WWtGeWVGZEVWWFJyTjFkelZqRm1iRWh2Y0d0aVdGcEljRWh5VDNkMldHWlRRa2hpT1ZGQmFVazBkMXBEZG1sQ1pqZE9NSFZsVFdsb1VESmthM0JzYlZ4dU5tWklMekZUYkdwa1pWVlNNV1ZKY21WV04yUkRRWEJpYVc1eU5rOVVTREZqVTA0MVZtTlplSE4yVWpoVU9UZ3JVVWxITDBaV2FtTTNhM05yU21KeU0xeHVkMEpUZEdoalVsaEtia3R0WmtvemVXVnhkMmRsTmtGQlEyZG5WMVpRVERSR2FuWm9OQzlSTW5SeFdrZENjV3hQV1hWNEx6UklWM1pUVTJWWVMxaDJjbHh1WVVSYWNrTm5TWEZPTVhCUlJWa3dhbTB5Wmt4SFpFOURSV2hGZGxSeFpFNDBkVzluYkUwMWNpc3lkVWxZYm5WRWFFb3ZRM1pMZEdkVFJXWklNM0JrZFZ4dWNsRkpSRUZSUVVKY2JpMHRMUzB0UlU1RUlGQlZRa3hKUXlCTFJWa3RMUzB0TFZ4dUlpd2lhMlY1VTJsbmJtRjBkWEpsSWpvaVpYbEtlbUZYWkhWWldGSXhZMjFWYVU5cFNsVk9iWEJ5VjJwQ01WUXhWalZaZW14M1RWaHJNMDlVVmxGT1IzQmhXV3RyTlZWcGRGcFJla0o2VlZkS2JWVXlNVk5hTW5oclZsWmtUa3N5ZERKaE1GWkNUVlJTYkdJeVdrbGxiVnBIWld0R1YxWkhNVU5rUkd3MFdrY3hUbFpZVmpSU01VWnlVVEZhV2s5RGRFWmtiV2hWVkVac2FWVlhOVEpoU0hCV1ZFVm9NVTF0ZUhSV1NFNVZZekZ2TVdKWVVuZFRNbGw0V2xoa1JHVklWa1pVYTJoNFVqQlNkR1JwZERaVmEwWnlUMVZGZDJOWFZuSldSRlp6V2xkNFdGWldTa1ZSV0c4elVqTnNSbG96YkRKaWFsSnpWakZvTldNeWVGVmtlbHBFWldwQ2VrNUhkSGxqUlVZMFpGYzBNazFzV1RCak0yeFZaRzVvYTJRd2VHcFRNRkowVDBWUk1FOVZXbWxaVlRGdFYxVmFSbU5HVG5Oa2FtaHhXVEI0VVU1SFZsSlpWMGswVjBWV1JXRkVTblJpYlRGdldtdDRTVk5IT1hKVlIxRjNWWHBuZWxGVmVHOU9WV3hDWlVaYVdVOVdiM1pVTUZaWVVteHNibHB0T1ZCVlJsSnRVekZLUmxkSGNIcFVlbGx5WkZad2EyUnNjRE5TUm1SM1VsYzVSMDFWT1VKYVZFSnJUWGs1Tm1OWGFETk9NRkl3VTBabk5WWnNiRTVMZWxwcVlteFJlV05IU210VGJFcDBZMVZWTVdGRVRuZFdhMVpPWW1wV01GSnNSak5YUlhCNFpESXhOV1ZWUlRsUVUwbHpTVzFrYzJJeVNtaGlSWFJzWlZWc2EwbHFiMmxaYlZKc1dsUlZNazVVV1hkWk1scHBUa1JPYWs5WFNYbFBSMHB0VDFSb2JGbFhUbWhhYlVVeVRrUlphV1pSUFQwaWZRPT0ifQ==
