apiVersion: kots.io/v1beta1
kind: License
metadata:
  name: communitybeta
spec:
  appSlug: gitpod
  channelID: 259YYCMTfMbbN8zxJSvlWjsBDEI
  channelName: Beta
  customerName: Community (Beta)
  endpoint: https://replicated.app
  entitlements:
    customerId:
      title: Customer ID
      value: ""
      valueType: String
    domain:
      title: Domain
      value: ""
      valueType: String
    expires_at:
      description: License Expiration
      title: Expiration
      value: ""
      valueType: String
    levelId:
      isHidden: true
      title: License level
      value: 1
      valueType: Integer
    seats:
      title: User seats
      value: 0
      valueType: Integer
  isGitOpsSupported: true
  isIdentityServiceSupported: true
  isNewKotsUiEnabled: true
  isSemverRequired: true
  isSnapshotSupported: true
  licenseID: 273KPoWTBv5agYR2ulVguz5lsFm
  licenseSequence: 7
  licenseType: community
  signature: eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pWTI5dGJYVnVhWFI1WW1WMFlTSjlMQ0p6Y0dWaklqcDdJbXhwWTJWdWMyVkpSQ0k2SWpJM00wdFFiMWRVUW5ZMVlXZFpVakoxYkZabmRYbzFiSE5HYlNJc0lteHBZMlZ1YzJWVWVYQmxJam9pWTI5dGJYVnVhWFI1SWl3aVkzVnpkRzl0WlhKT1lXMWxJam9pUTI5dGJYVnVhWFI1SUNoQ1pYUmhLU0lzSW1Gd2NGTnNkV2NpT2lKbmFYUndiMlFpTENKamFHRnVibVZzU1VRaU9pSXlOVGxaV1VOTlZHWk5ZbUpPT0hwNFNsTjJiRmRxYzBKRVJVa2lMQ0pqYUdGdWJtVnNUbUZ0WlNJNklrSmxkR0VpTENKc2FXTmxibk5sVTJWeGRXVnVZMlVpT2pjc0ltVnVaSEJ2YVc1MElqb2lhSFIwY0hNNkx5OXlaWEJzYVdOaGRHVmtMbUZ3Y0NJc0ltVnVkR2wwYkdWdFpXNTBjeUk2ZXlKamRYTjBiMjFsY2tsa0lqcDdJblJwZEd4bElqb2lRM1Z6ZEc5dFpYSWdTVVFpTENKMllXeDFaU0k2SWlJc0luWmhiSFZsVkhsd1pTSTZJbE4wY21sdVp5SjlMQ0prYjIxaGFXNGlPbnNpZEdsMGJHVWlPaUpFYjIxaGFXNGlMQ0oyWVd4MVpTSTZJaUlzSW5aaGJIVmxWSGx3WlNJNklsTjBjbWx1WnlKOUxDSmxlSEJwY21WelgyRjBJanA3SW5ScGRHeGxJam9pUlhod2FYSmhkR2x2YmlJc0ltUmxjMk55YVhCMGFXOXVJam9pVEdsalpXNXpaU0JGZUhCcGNtRjBhVzl1SWl3aWRtRnNkV1VpT2lJaUxDSjJZV3gxWlZSNWNHVWlPaUpUZEhKcGJtY2lmU3dpYkdWMlpXeEpaQ0k2ZXlKMGFYUnNaU0k2SWt4cFkyVnVjMlVnYkdWMlpXd2lMQ0oyWVd4MVpTSTZNU3dpZG1Gc2RXVlVlWEJsSWpvaVNXNTBaV2RsY2lJc0ltbHpTR2xrWkdWdUlqcDBjblZsZlN3aWMyVmhkSE1pT25zaWRHbDBiR1VpT2lKVmMyVnlJSE5sWVhSeklpd2lkbUZzZFdVaU9qQXNJblpoYkhWbFZIbHdaU0k2SWtsdWRHVm5aWElpZlgwc0ltbHpSMmwwVDNCelUzVndjRzl5ZEdWa0lqcDBjblZsTENKcGMwbGtaVzUwYVhSNVUyVnlkbWxqWlZOMWNIQnZjblJsWkNJNmRISjFaU3dpYVhOVGJtRndjMmh2ZEZOMWNIQnZjblJsWkNJNmRISjFaU3dpYVhOT1pYZExiM1J6VldsRmJtRmliR1ZrSWpwMGNuVmxMQ0pwYzFObGJYWmxjbEpsY1hWcGNtVmtJanAwY25WbGZYMD0iLCJpbm5lclNpZ25hdHVyZSI6ImV5SnNhV05sYm5ObFUybG5ibUYwZFhKbElqb2lVSHBWZFZaVWRESmxSa2RSU0dWNVMwSlVVMVpNVDNoT09HNXlRV0ZNVFM5SU0yRnpUREZGUldwUVdsTTNUbEJGYnpka0szUXlXbU5OWm5GNVEzWldiMGhTWm5JMUt6UnJVVTFMYld4YVlrcGtlWFl4ZUdrMWMxcGFTWEZFYlRsaE9WSjZaV2RRUzJadk9YTmtNbUVyYVVGNlUwSlNjUzlOTVV4NWEyTnRSVkZOWTNBME5FSmhOVEpHYkhwMk5taGFTRnBHTjJwTWVWTlZOV3BUVjFCWVNqTm1ObGh4UkV0T2RuWlhZbUUyZG5wdmVHbGFPR3QwT1VKVk1UTjZWbWx6TVU5TmQyaEVlVXBFV0RJMGMzZzFRVUpKV1c1R01XcEtibWQxY0dkMk9VbG1hMnRKVlc5TWRHRnhkV3gyY0dWRVpsVk1XV1pxS3pSSWNWTlZZaTlLTkUxSVJsWkpVbk5HWkU5clVrUkVSMlY2UlVoTlRqRlNUbEUyUjBsalYwdGFSbk5MU0hCWVFXbHVXRTg0YXpWRmFWbEJSbVp6ZVRreGFHTnlaR3hsVjB0VmQzRlRSMUkxYmpKa2Jtd3dNV1ptTDNKblpYcEJQVDBpTENKd2RXSnNhV05MWlhraU9pSXRMUzB0TFVKRlIwbE9JRkJWUWt4SlF5QkxSVmt0TFMwdExWeHVUVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRnZOVzU2T1ZsRVMxTlJSbVZ3YjJKYVZqQTVkMXh1V0V0bE4zUnNURlZWVlc1VFpUZ3dNRWREUzFSRFZGcHpibTlxZFVKaGVXcHBTMlIzV2tRelZWUktjVEJFYVc5QmNsaFZhMmhFTkd0bWRETnRSRlEzUmx4dVlrRnllRmRFVlhSck4xZHpWakZtYkVodmNHdGlXRnBJY0VoeVQzZDJXR1pUUWtoaU9WRkJhVWswZDFwRGRtbENaamRPTUhWbFRXbG9VREprYTNCc2JWeHVObVpJTHpGVGJHcGtaVlZTTVdWSmNtVldOMlJEUVhCaWFXNXlOazlVU0RGalUwNDFWbU5aZUhOMlVqaFVPVGdyVVVsSEwwWldhbU0zYTNOclNtSnlNMXh1ZDBKVGRHaGpVbGhLYmt0dFprb3plV1Z4ZDJkbE5rRkJRMmRuVjFaUVREUkdhblpvTkM5Uk1uUnhXa2RDY1d4UFdYVjRMelJJVjNaVFUyVllTMWgyY2x4dVlVUmFja05uU1hGT01YQlJSVmt3YW0weVpreEhaRTlEUldoRmRsUnhaRTQwZFc5bmJFMDFjaXN5ZFVsWWJuVkVhRW92UTNaTGRHZFRSV1pJTTNCa2RWeHVjbEZKUkVGUlFVSmNiaTB0TFMwdFJVNUVJRkJWUWt4SlF5QkxSVmt0TFMwdExWeHVJaXdpYTJWNVUybG5ibUYwZFhKbElqb2laWGxLZW1GWFpIVlpXRkl4WTIxVmFVOXBTbWhhYTNoSVVtNWFUVk50U205U1JtZzJZa2hPV2sxdVZtaFNWRXA2WTFaR05GUXhhRWRTUjBaUVpXMTRZVTR5WTNaaU1XaFpXVlJzVlZaV1FYSmhNR1JMVkRGa1ExTldWakppV0dSSFREQnJORnBJVG0xWldGcHVWWHBvUTFWSFpESlVNVXB2WldwQ2RGTklTbk5TVlVVMFVtdHNXbEl6YUhWa1JHaG9Wa1YwYkZJeWFHOVRWVlV5WTFSSk5FMVdVVEZPVlRGRVpESnNOVXQ2VFhKaGVYUlhZVVpyZVZGV2FIUlVhMlJIVVhwU1ZHSnROWGRXZWtFeVZucGFjVkpyUm14VVZ6RjRWVVUwTlZGV1NtOVhXRUpxWWxOME1GTXdZekZTYWtaR1pFaFNTMWRVVFRKV2FrNUZVVlJDUWxReldteE9SV1JDVkRBNVJtVnJWa3BOU0VKRVZWaGFNMk5WY0hObGJWWk5aVlJzYWsxSE9WQmFNRVpZV1cxYVIxWnRTazVMTUU1RVYxWmtSR1ZXUmpGalYzUkRWakZKTTFWWVRrbGpSbWhzVGtSTk5WUnNaRE5hUmtKWFVsZFJkbEY2Ykdwak0yeHVWRVpPY2xWdVpFdFhhMFl6VFhwYVdWZEZWbkZoU0ZKeFdrZGtXRXd6Vm5kaFJHUXlZak5HYWs1R1VteFRhbFl3VmxWYVNrNVliSFZTVlZwWVZsVTRNVlJzYUZGa1ZtczFaVVJPZVZWWE9WWlBWVXB4WkZaQk1VNXJWa2xsU0d4SldtMU9TazlXYkhCV01YQk9WVEk1ZEU5SVl6bFFVMGx6U1cxa2MySXlTbWhpUlhSc1pWVnNhMGxxYjJsWmJWSnNXbFJWTWs1VVdYZFpNbHBwVGtST2FrOVhTWGxQUjBwdFQxUm9iRmxYVG1oYWJVVXlUa1JaYVdaUlBUMGlmUT09In0=
