apiVersion: kots.io/v1beta1
kind: License
metadata:
  name: community
spec:
  appSlug: gitpod
  channelID: 259YYBILXTa30S1Soli9YcWcPTb
  channelName: Stable
  customerName: Community
  endpoint: https://replicated.app
  entitlements:
    customerId:
      title: Customer ID
      value: ""
      valueType: String
    domain:
      title: Domain
      value: ""
      valueType: String
    expires_at:
      description: License Expiration
      title: Expiration
      value: ""
      valueType: String
    levelId:
      isHidden: true
      title: License level
      value: 1
      valueType: Integer
    seats:
      title: User seats
      value: 0
      valueType: Integer
  isGitOpsSupported: true
  isIdentityServiceSupported: true
  isNewKotsUiEnabled: true
  isSemverRequired: true
  isSnapshotSupported: true
  licenseID: 273WZe6zHEcVHGOuIAviuyGXbgm
  licenseSequence: 10
  licenseType: community
  signature: eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pWTI5dGJYVnVhWFI1SW4wc0luTndaV01pT25zaWJHbGpaVzV6WlVsRUlqb2lNamN6VjFwbE5ucElSV05XU0VkUGRVbEJkbWwxZVVkWVltZHRJaXdpYkdsalpXNXpaVlI1Y0dVaU9pSmpiMjF0ZFc1cGRIa2lMQ0pqZFhOMGIyMWxjazVoYldVaU9pSkRiMjF0ZFc1cGRIa2lMQ0poY0hCVGJIVm5Jam9pWjJsMGNHOWtJaXdpWTJoaGJtNWxiRWxFSWpvaU1qVTVXVmxDU1V4WVZHRXpNRk14VTI5c2FUbFpZMWRqVUZSaUlpd2lZMmhoYm01bGJFNWhiV1VpT2lKVGRHRmliR1VpTENKc2FXTmxibk5sVTJWeGRXVnVZMlVpT2pFd0xDSmxibVJ3YjJsdWRDSTZJbWgwZEhCek9pOHZjbVZ3YkdsallYUmxaQzVoY0hBaUxDSmxiblJwZEd4bGJXVnVkSE1pT25zaVkzVnpkRzl0WlhKSlpDSTZleUowYVhSc1pTSTZJa04xYzNSdmJXVnlJRWxFSWl3aWRtRnNkV1VpT2lJaUxDSjJZV3gxWlZSNWNHVWlPaUpUZEhKcGJtY2lmU3dpWkc5dFlXbHVJanA3SW5ScGRHeGxJam9pUkc5dFlXbHVJaXdpZG1Gc2RXVWlPaUlpTENKMllXeDFaVlI1Y0dVaU9pSlRkSEpwYm1jaWZTd2laWGh3YVhKbGMxOWhkQ0k2ZXlKMGFYUnNaU0k2SWtWNGNHbHlZWFJwYjI0aUxDSmtaWE5qY21sd2RHbHZiaUk2SWt4cFkyVnVjMlVnUlhod2FYSmhkR2x2YmlJc0luWmhiSFZsSWpvaUlpd2lkbUZzZFdWVWVYQmxJam9pVTNSeWFXNW5JbjBzSW14bGRtVnNTV1FpT25zaWRHbDBiR1VpT2lKTWFXTmxibk5sSUd4bGRtVnNJaXdpZG1Gc2RXVWlPakVzSW5aaGJIVmxWSGx3WlNJNklrbHVkR1ZuWlhJaUxDSnBjMGhwWkdSbGJpSTZkSEoxWlgwc0luTmxZWFJ6SWpwN0luUnBkR3hsSWpvaVZYTmxjaUJ6WldGMGN5SXNJblpoYkhWbElqb3dMQ0oyWVd4MVpWUjVjR1VpT2lKSmJuUmxaMlZ5SW4xOUxDSnBjMGRwZEU5d2MxTjFjSEJ2Y25SbFpDSTZkSEoxWlN3aWFYTkpaR1Z1ZEdsMGVWTmxjblpwWTJWVGRYQndiM0owWldRaU9uUnlkV1VzSW1selUyNWhjSE5vYjNSVGRYQndiM0owWldRaU9uUnlkV1VzSW1selRtVjNTMjkwYzFWcFJXNWhZbXhsWkNJNmRISjFaU3dpYVhOVFpXMTJaWEpTWlhGMWFYSmxaQ0k2ZEhKMVpYMTkiLCJpbm5lclNpZ25hdHVyZSI6ImV5SnNhV05sYm5ObFUybG5ibUYwZFhKbElqb2lXR0ZpYURKR2ExY3JTWFZFV1dKVWVWWTNiak4yVWtsMFpERTRSMkZsT0dFd1EwZENNSGhCUW5BcmVucENRMkp5VkVObUwySnZNbEV4U0d0aFlraHVRM1lyTUZZMGNsSjFia3hTUTFwcFlreE1jM2htWjFsSFZqQllMMXBCUVZaWWNXcHFNSGgyTkcxU1RuTmtSRFJQUldGU1ZYQTBVRzlZV25wb2RHeHNZbkoxTW5waFFrMVhibEJzYjJaclRFcDFXbTVoV1RoWVNqUkxhVXBOYWsxdFdqUlFhekYyZUhaU1lqbHJUWFE1VUU5aWFsVTFVR0ZYWjA1RWVVNHJMM0JMYUZocVdqUjRXbTlFZWpCVmRWTXhVMlJhWnpJNVVUSkdXakp6TkVWNU9VaGtkMmxZVjB4S2QzWjFZMkZOTjNOSWREaHVNR0pSYWpFM05GSk1aMWxDWmpSQlZHRk9ZbWd3TnpaTFNqQnhWRXhsTDBNd1NFOXJPR1ZZT0ZkdVFtVjFSa0ZrVkU1dWNsbFFjSFlyT0ZCd01VSTVVVTlxV1dFNVVGTmlTekZ0THpOQmNqVkZjRmxUUlc5bFEwMDNOMlJWUW1wSlJVOTNQVDBpTENKd2RXSnNhV05MWlhraU9pSXRMUzB0TFVKRlIwbE9JRkJWUWt4SlF5QkxSVmt0TFMwdExWeHVUVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRnZOVzU2T1ZsRVMxTlJSbVZ3YjJKYVZqQTVkMXh1V0V0bE4zUnNURlZWVlc1VFpUZ3dNRWREUzFSRFZGcHpibTlxZFVKaGVXcHBTMlIzV2tRelZWUktjVEJFYVc5QmNsaFZhMmhFTkd0bWRETnRSRlEzUmx4dVlrRnllRmRFVlhSck4xZHpWakZtYkVodmNHdGlXRnBJY0VoeVQzZDJXR1pUUWtoaU9WRkJhVWswZDFwRGRtbENaamRPTUhWbFRXbG9VREprYTNCc2JWeHVObVpJTHpGVGJHcGtaVlZTTVdWSmNtVldOMlJEUVhCaWFXNXlOazlVU0RGalUwNDFWbU5aZUhOMlVqaFVPVGdyVVVsSEwwWldhbU0zYTNOclNtSnlNMXh1ZDBKVGRHaGpVbGhLYmt0dFprb3plV1Z4ZDJkbE5rRkJRMmRuVjFaUVREUkdhblpvTkM5Uk1uUnhXa2RDY1d4UFdYVjRMelJJVjNaVFUyVllTMWgyY2x4dVlVUmFja05uU1hGT01YQlJSVmt3YW0weVpreEhaRTlEUldoRmRsUnhaRTQwZFc5bmJFMDFjaXN5ZFVsWWJuVkVhRW92UTNaTGRHZFRSV1pJTTNCa2RWeHVjbEZKUkVGUlFVSmNiaTB0TFMwdFJVNUVJRkJWUWt4SlF5QkxSVmt0TFMwdExWeHVJaXdpYTJWNVUybG5ibUYwZFhKbElqb2laWGxLZW1GWFpIVlpXRkl4WTIxVmFVOXBTbFpWTVdoelRVUk9WMXBzWnpSaVV6bGFWVzVXZFdOVmFFaGhTRTB4WkdwR1dWZHRVbEJSTWxwTlQwVjRRbUpHVms1TmExcFNUakF4V21NeFRUSmpNSGhPVmtkYWJtRldXazFrV0VwdFYxaGtlbVJ0U25CWk1FWnpVVmRhYmxSWGVEWlhWV2h6VFZoT2NHVlZkR0ZYUlZvelVWaEdibHA2YUVOVlZXeHNXVE5vYUdWWE9YVlVSbVJhWlcxMFJVMXVSazlhVkUxM1VrTTVkMUpWVmpCUFJrRXdXV2wwUzAxVk1XeFNVemw1VlVkV2QwNTZVbFJrTUhCRlRXMWtSRTlYWkUxVFIyaDBUV3hDYlZGWWNHaFJWRlkwWWtSc1RWWlhUbGhXVlVwM1dUTk9lR1ZFUlhkU1Z6QXdaRVZXTldSc2FGQmtTR3d3VkZSU1RHSnNRbWhTZWsweFRqSkdObUpxWkZsaVIxcFJZVmhPVDFkSFpIZFdibWd3VTBkWmRsTkZXa2hUZWtFelZXdFpNR1Z1UlRSV1ZXeFJWRlJTY1ZKR2FHcE9SMFkxWWxWa01WRXlXVE5NTTBKTldtcHNiMDR4Um5KU1dFMDBZVmRrYjFacVZqRlJWR1JhVkZkT1MyVkhTa1ZXUnpWelkycFZlV05xUW10VVZtdDNVV2x6TldWVVZqUmthekV3WlZVNVJGcFhZekJOTUhSTFN6RndhRll5YURGT00yUkpWVmhzUkZORWJGcGFNM0JEVDBkYU5tUnJVa3BQUlZKV1pFaGtjRTVVUW14TmFscHRUVlZHY2xWc1JUbFFVMGx6U1cxa2MySXlTbWhpUlhSc1pWVnNhMGxxYjJsWmJWSnNXbFJWTWs1VVdYZFpNbHBwVGtST2FrOVhTWGxQUjBwdFQxUm9iRmxYVG1oYWJVVXlUa1JaYVdaUlBUMGlmUT09In0=
