apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    component: workspace
spec:
  schedulerName: gitpod-scheduler
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
