packages:
  - name: app
    type: yarn
    srcs:
      - "src/**"
      - "ee/**"
      - "test/**"
      - package.json
      - mocha.opts
    deps:
      - components/content-service-api/typescript:lib
      - components/gitpod-db:lib
      - components/gitpod-messagebus:lib
      - components/gitpod-protocol:lib
      - components/image-builder-api/typescript:lib
      - components/licensor/typescript:lib
      - components/ws-manager-api/typescript:lib
    config:
      packaging: offline-mirror
      yarnLock: ${coreYarnLockBase}/yarn.lock
      tsconfig: tsconfig.json
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/server:${version}
  - name: lib
    type: yarn
    srcs:
      - "src/**"
      - "ee/**"
      - "test/**"
      - package.json
      - mocha.opts
    deps:
      - components/content-service-api/typescript:lib
      - components/gitpod-db:lib
      - components/gitpod-messagebus:lib
      - components/gitpod-protocol:lib
      - components/image-builder-api/typescript:lib
      - components/licensor/typescript:lib
      - components/ws-manager-api/typescript:lib
    config:
      packaging: library
      yarnLock: ${coreYarnLockBase}/yarn.lock
      tsconfig: tsconfig.json
      commands:
        test: ["yarn", "test"]
        build: ["npx", "tsc"]
scripts:
  - name: telepresence
    script: |
      kubectl patch deployment server --patch "$(cat server-deploy-telepresence.yaml)" && \
      env TELEPRESENCE_USE_DEPLOYMENT=1 telepresence --swap-deployment server \
                   --method inject-tcp \
                   --run yarn start-inspect | \
        leeway run components:dejson-log-output

      kubectl patch deployment server --patch "$(cat server-deploy-post-telepresence.yaml)"
