packages:
  - name: app
    type: go
    srcs:
      - "testdata/**"
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    deps:
      - components/common-go/log:lib
      - components/gitpod-protocol/go:lib
      - components/supervisor-api/go:lib
    config:
      packaging: app
      buildCommand: ["go", "build", "-trimpath", "-ldflags", "-buildid= -w -s -X 'github.com/gitpod-io/gitpod/jetbrains/status.Version=commit-${__git_commit}'"]
