packages:
  - name: app
    type: go
    srcs:
      - go.mod
      - go.sum
      - "**/*.go"
      - "**/*.c"
    deps:
      - components/common-go/log:lib
      - components/common-go/nsenter:lib
      - components/content-service-api/go:lib
      - components/ws-daemon-api/go:lib
    config:
      packaging: app
      buildCommand: ["go", "build", "-ldflags", "-w -extldflags \"-static\""]
