on:
  pull_request:
    paths:
    - install/installer/pkg/components/spicedb/data/**
name: SpiceDB Authorization Validation
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    name: Validate spicedb schema and assertions
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate SpiceDB schema
      uses: authzed/action-spicedb-validate@v1.0.1
      with:
        validationfile: "install/installer/pkg/components/spicedb/data/schema.yaml"
