name: Build
on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  image:
    if: ${{ contains(github.event.pull_request.body, '[x] /werft with-github-actions') }}
    runs-on: [self-hosted]
    container:
      image: gitpod/workspace-full:latest
    outputs:
      devimage: ${{ steps.image.outputs.devimage }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1000
      - name: Configure workspace
        run: |
          cp -r /__w/gitpod/gitpod /workspace
          # Needed by google-github-actions/setup-gcloud
          sudo chown -R gitpod:gitpod /__t
          # Needed by docker/login-action
          sudo chmod goa+rw /var/run/docker.sock
      - name: Install Leeway
        shell: bash
        working-directory: /workspace/gitpod
        run: |
          LEEWAY_VERSION=0.7.3
          cd /usr/bin && sudo curl -fsSL https://github.com/gitpod-io/leeway/releases/download/v${LEEWAY_VERSION}/leeway_${LEEWAY_VERSION}_Linux_x86_64.tar.gz | sudo tar xz
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - uses: docker/login-action@v2
        with:
          registry: eu.gcr.io
          username: oauth2accesstoken
          password: "${{ steps.auth.outputs.access_token }}"
      - name: Probe If Image Exists
        id: image
        shell: bash
        working-directory: /workspace/gitpod
        run: |
          pwd
          ls -l
          RESULT=""
          IMG_VERSION="img-$(git log -n 1 --pretty=format:%H dev/image/)"
          IMG_BASE="eu.gcr.io/gitpod-core-dev/dev"
          IMG_NAME="$IMG_BASE/dev-environment:$IMG_VERSION"

          echo "Probing for image $IMG_NAME"
          docker manifest inspect "$IMG_NAME" || RESULT="missing"

          echo "IMG_VERSION=$IMG_VERSION" >> $GITHUB_ENV
          echo "IMG_BASE=$IMG_BASE"       >> $GITHUB_ENV
          echo "IMG_MISSING=$RESULT"      >> $GITHUB_ENV

          echo "devimage=$IMG_NAME" >> $GITHUB_OUTPUT

          # sleep 10000

      - name: Build Image
        if: ${{ env.IMG_MISSING }}
        shell: bash
        working-directory: /workspace/gitpod
        run: |
          RESULT=0
          leeway build dev/image:docker \
            -Dversion=$IMG_VERSION \
            -DimageRepoBase=$IMG_BASE \
            --report report.html || RESULT=$?
          cat report.html >> $GITHUB_STEP_SUMMARY
          exit $RESULT

  previewctl:
    if: ${{ contains(github.event.pull_request.body, '[x] /werft with-github-actions') && contains(github.event.pull_request.body, '[x] /werft with-preview') }}
    runs-on: [self-hosted]
    needs: [image]
    container:
      image: ${{ needs.image.outputs.devimage }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure workspace
        run: cp -r /__w/gitpod/gitpod /workspace
      - name: Build previewctl
        shell: bash
        working-directory: /workspace/gitpod
        run: |
          leeway run dev/preview/previewctl:install --dont-test
          cp /workspace/bin/previewctl /__w/gitpod/gitpod/previewctl
      - name: "Upload Installer artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: previewctl
          path: previewctl

  infrastructure:
    runs-on: [self-hosted]
    needs: [previewctl]
    container:
      image: ${{ needs.image.outputs.devimage }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: previewctl
      - name: Configure workspace
        run: |
          cp -r /__w/gitpod/gitpod /workspace
          chmod +x ./previewctl
          sudo mv ./previewctl /usr/local/bin/
      - name: Terraform
        id: terraform
        shell: bash
        working-directory: /workspace/gitpod
        env:
          HOME: /home/gitpod
          PREVIEW_ENV_DEV_SA_KEY: ${{ secrets.GCP_CREDENTIALS }}
          PREVIEW_ENV_DEV_SA_KEY_PATH: /home/gitpod/.config/gcloud/preview-environment-dev-sa.json
          # Don't prompt user before terraform apply
          TF_INPUT: 0
          TF_IN_AUTOMATION: true
        run: |
          echo "${PREVIEW_ENV_DEV_SA_KEY}" > "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
          gcloud auth activate-service-account --key-file "${PREVIEW_ENV_DEV_SA_KEY_PATH}"

          previewctl get-credentials --gcp-service-account "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
          leeway run dev/preview:create-preview

  build:
    if: ${{ contains(github.event.pull_request.body, '[x] /werft with-github-actions') }}
    runs-on: [self-hosted]
    needs: [image]
    outputs:
      version: ${{ steps.leeway.outputs.version }}
    container:
      image: ${{ needs.image.outputs.devimage }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure workspace
        run: |
          cp -r /__w/gitpod/gitpod /workspace
          # Needed by google-github-actions/setup-gcloud
          sudo chown -R gitpod:gitpod /__t
          # Needed by docker/login-action
          sudo chmod goa+rw /var/run/docker.sock
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - uses: docker/login-action@v2
        with:
          registry: eu.gcr.io
          username: oauth2accesstoken
          password: "${{ steps.auth.outputs.access_token }}"
      - name: "Determine Branch"
        id: branches
        uses: transferwise/sanitize-branch-name@v1
      - name: Leeway Vet
        shell: bash
        working-directory: /workspace/gitpod
        run: |
          leeway vet --ignore-warnings
      - name: Leeway Build components:all-ci
        id: leeway
        shell: bash
        working-directory: /workspace/gitpod
        env:
          JAVA_HOME: /home/gitpod/.sdkman/candidates/java/current
          VERSION: "${{ steps.branches.outputs.sanitized-branch-name }}.${{github.run_number}}"
        run: |
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          RESULT=0
          leeway build components:all-ci \
            -Dversion=$VERSION \
            -DSEGMENT_IO_TOKEN=value \
            -DpublishToNPM=false \
            --dont-test \
            --report report.html || RESULT=$?

          cat report.html >> $GITHUB_STEP_SUMMARY
          cp /tmp/versions.yaml /__w/gitpod/gitpod/versions.yaml
          cp /tmp/installer /__w/gitpod/gitpod/installer

          exit $RESULT
      - name: "Upload Installer artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: installer-artifacts
          path: |
            versions.yaml
            installer

  install:
    needs: [previewctl, build, infrastructure]
    runs-on: [self-hosted]
    container:
      image: ${{ needs.image.outputs.devimage }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure workspace
        run: |
          cp -r /__w/gitpod/gitpod /workspace
          # Needed by google-github-actions/setup-gcloud
          sudo chown -R gitpod:gitpod /__t
      - uses: actions/download-artifact@v3
        with:
          name: installer-artifacts
      - uses: actions/download-artifact@v3
        with:
          name: previewctl
      - name: Install artifacts
        run: |
          cp versions.yaml /tmp/versions.yaml
          chmod +x ./installer
          sudo mv ./installer /usr/local/bin/
          chmod +x ./previewctl
          sudo mv ./previewctl /usr/local/bin/
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install
        shell: bash
        working-directory: /workspace/gitpod
        env:
          VERSION: ${{needs.build.outputs.version}}
          HOME: /home/gitpod
          PREVIEW_ENV_DEV_SA_KEY: ${{ secrets.GCP_CREDENTIALS }}
          PREVIEW_ENV_DEV_SA_KEY_PATH: /home/gitpod/.config/gcloud/preview-environment-dev-sa.json
        run: |
          echo "${PREVIEW_ENV_DEV_SA_KEY}" > "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
          previewctl install-context --timeout 10m --gcp-service-account "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
          leeway run dev/preview:deploy-gitpod
          previewctl report >> $GITHUB_STEP_SUMMARY

  monitoring:
    needs: [previewctl, infrastructure]
    runs-on: [self-hosted]
    container:
      image: ${{ needs.image.outputs.devimage }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure workspace
        run: |
          cp -r /__w/gitpod/gitpod /workspace
          # Needed by google-github-actions/setup-gcloud
          sudo chown -R gitpod:gitpod /__t
      - uses: actions/download-artifact@v3
        with:
          name: previewctl
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Install artifacts
        run: |
          chmod +x ./previewctl
          sudo mv ./previewctl /usr/local/bin/
      - name: Install
        shell: bash
        working-directory: /workspace/gitpod
        env:
          HOME: /home/gitpod
          PREVIEW_ENV_DEV_SA_KEY: ${{ secrets.GCP_CREDENTIALS }}
          PREVIEW_ENV_DEV_SA_KEY_PATH: /home/gitpod/.config/gcloud/preview-environment-dev-sa.json
        run: |
          echo "${PREVIEW_ENV_DEV_SA_KEY}" > "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
          previewctl install-context --timeout 10m --gcp-service-account "${PREVIEW_ENV_DEV_SA_KEY_PATH}"
          leeway run dev/preview:deploy-monitoring-satellite
          echo '<p>Monitoring satellite has been installed in your preview environment.</p>' >> $GITHUB_STEP_SUMMARY
          echo '<ul>' >> $GITHUB_STEP_SUMMARY
          echo '<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/f2938b2bcb0c4c8c99afe1d2b872380e" target="_blank">internal documentation</a> on how to use it.</li>' >> $GITHUB_STEP_SUMMARY
          echo '</ul>' >> $GITHUB_STEP_SUMMARY
