name: Check for new JetBrains IDE releases
on:
  schedule:
    # At 11:00 on every day-of-week from Monday through Friday.
    - cron: "0 11 * * 1-5"

jobs:
  intellij:
    uses: gitpod-io/gitpod/.github/workflows/jetbrains-updates-template.yml@main
    with:
      productName: IntelliJ IDEA
      productId: intellij
      productCode: IIU
      productType: release
  intellij-eap:
    uses: gitpod-io/gitpod/.github/workflows/jetbrains-updates-template.yml@main
    with:
      productName: IntelliJ IDEA (EAP)
      productId: intellij-eap
      productCode: IIU
      productType: release%2Ceap%2Crc
  goland:
    uses: gitpod-io/gitpod/.github/workflows/jetbrains-updates-template.yml@main
    with:
      productName: GoLand
      productId: goland
      productCode: GO
      productType: release
  goland-eap:
    uses: gitpod-io/gitpod/.github/workflows/jetbrains-updates-template.yml@main
    with:
      productName: GoLand (EAP)
      productId: goland-eap
      productCode: GO
      productType: release%2Ceap%2Crc
