name: permissions
on:
  pull_request:
    paths:
    - install/installer/pkg/components/spicedb/data/schema.yaml
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v3
    - uses: "authzed/action-spicedb-validate@v1"
      with:
        validationfile: "install/installer/pkg/components/spicedb/data/schema.yaml"
