---
name: "Publish draft pre-release"

on:
  push:
    tags:
      - "*-rc*"

jobs:
  get-branch:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source code
      uses: actions/checkout@v1
    - name: Get Branch
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        branch=${raw/origin\/}
        echo ::set-env name=BRANCH::$branch

  generate-release-note:
    needs: [get-branch]
    runs-on: ubuntu-latest
    container: eu.gcr.io/gitpod-core-dev/dev/changelog:0.0.36
    steps:
      - uses: actions/checkout@v2
      - run: |
          export PR_BRANCH=${{ env.BRANCH }}
          git checkout -b $PR_BRANCH
          /app/changelog release-note -t $TOKEN -o gitpod-io -r gitpod -b $GITHUB_REF
          if [[ $(git status --porcelain) ]]; then
            git config --global user.name $GITHUB_USER
            git config --global user.email $GITHUB_EMAIL
            git add CHANGELOG.md
            git commit -m "[release-note] upload release note"
            git push origin $PR_BRANCH
          fi
        env:
          GITHUB_USER: roboquat
          GITHUB_EMAIL: roboquat@gitpod.io
          TOKEN: ${{ secrets.ROBOQUAT_AUTOMATIC_CHANGELOG }}
        shell: bash

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: [get-branch, generate-release-note]

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          draft: true
