---
name: "Publish draft pre-release"

on:
  push:
    tags:
      - "*-rc*"

jobs:
  generate-release-note:
    runs-on: ubuntu-latest
    container: eu.gcr.io/gitpod-core-dev/dev/changelog:0.0.36
    steps:
      - uses: actions/checkout@v2
      - run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          export PR_BRANCH=${raw/origin\/}
          git checkout -b $PR_BRANCH
          echo "testing" > install/installer/docs/release-note.md
          if [[ $(git status --porcelain) ]]; then
            git config --global user.name $GITHUB_USER
            git config --global user.email $GITHUB_EMAIL
            git add install/installer/docs/release-note.md
            git commit -m "[release-note] upload release note"
            git push origin $PR_BRANCH
          fi
        env:
          GITHUB_USER: roboquat
          GITHUB_EMAIL: roboquat@gitpod.io
          TOKEN: ${{ secrets.ROBOQUAT_AUTOMATIC_CHANGELOG }}
        shell: bash

  release:
    needs: [generate-release-note]
    runs-on: ubuntu-latest
    steps:
    - name: Get release note
      id: vars
      run: echo ::set-output name=releasenote::$(cat install/installer/docs/release-note.md)
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.ROBOQUAT_AUTOMATIC_CHANGELOG }}
      with:
        tag_name: <tofill>
        release_name: <tofill>
        draft: true
        prerelease: false
        body: |
          ${{ steps.note.outputs.releasenote }}
